# Site Settings
title                     : "Flat theme"
title_separator           : "|"
favicon                   : /test/assets/fav.ico
csstheme                  : "site"
similar_posts:
  tags_to_match: 2

# Site SEO
seo:
  gtmid: GTM-M3MXT24

# Site Header
main_logo                 : "https://s.gravatar.com/avatar/57ab9065cb1800ee75c6a34f27d78707?s=192"
name                      : "Hardik Dabhi"
description               : "Software Developer, Applications<span class='mx-2'>&#8226;</span><a target='_blank' href='https://github.com/hardikdabhi'>@hardikdabhi</a>"
header:
  links:
    - label: ""
      icon: "fab fa-github fa-2x"
      url: https://www.instagram.com/hardikdabhi22/

# site landing
landing:
  shop: 

# site post
post:
  sidebar: 

# Site Footer
copyright: "Developed using Jekyll & Github pages"
footer:
  insta_at: 2321794898.c625d4b.52d85f33c6074769a1052765b092bc06
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/hardikdabhi22/

# Sass/SCSS
sass:
  style: compressed
  sass_dir: _sass

# Reading Files
include:
  - _pages

# config
permalink: /:title
collections_dir: test