# Site Settings
title                     : "Site Title"
title_separator           : "|"

# Site Header
main_logo                 : ""
name                      : "Flat theme"
description               : "Hardpool Jekyll simple flat theme."
copyright                 : "Team Hardpool"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Sass/SCSS
sass:
  style: compressed

# Reading Files
include:
  - _pages